[theme]
name = "slick"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
name = "awesome5"

[[block]]
block = "music"

[[block]]
block = "cpu"
interval = 1
format = "E5-1650v3 {barchart} {utilization}% {frequency}Ghz"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "M: {MUg}Gb | C: {Cg}Gb | S: {SUg}Gb"
clickable = false

[[block]]
block = "net"
device = "eno1"
interval = 2
speed_digits = 2
format = "{graph_down} {speed_down} {graph_up} {speed_up}" 

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"

[[block]]
block = "sound"
step_width = 2

