[theme]
name = "slick"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
name = "awesome5"

[[block]]
block = "cpu"
interval = 1
format = "E5-1650v3 {barchart} {utilization}% {frequency}Ghz"

[[block]]
block = "temperature"
collapsed = false
good = 50
idle = 55
info = 60
warning = 70
# alert = 80

[[block]]
block = "load"
interval = 1
format = "1m: {1m} 5m: {5m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "M: {MUg}Gb | C: {Cg}Gb | S: {SUg}Gb"
clickable = false

[[block]]
block = "time"
interval = 1
format = "%a %d/%m %r"

[[block]]
block = "sound"
step_width = 2

