[theme]
name = "slick"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
name = "awesome5"

[[block]]
block = "nvidia_gpu"
label = "1050 TI"
show_clocks = true

[[block]]
block = "temperature"
collapsed = false
good = 50
idle = 55
info = 60
warning = 70
# alert = 80

[[block]]
block = "load"
interval = 1
format = "1m: {1m} 5m: {5m}"

[[block]]
block = "time"
interval = 1
format = "%R"

[[block]]
block = "sound"
step_width = 2

