[theme]
name = "slick"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
name = "awesome5"

[[block]]
block = "nvidia_gpu"
label = "1050 TI"
show_clocks = true

[[block]]
block = "music"
buttons = ["play", "next"]
max_width = 41

# [[block]]
# block = "time"
# interval = 1
# format = "%R"
# 
[[block]]
block = "sound"
step_width = 2

